### ISSUE TITLE
Api watch crash

### ISSUE THREAD

**Issue by Sigri44** [sismo-core/sismo-hub#287]
CPU : M1 ARM
OS : 12.5.1

When use `yarn api:watch` command, result : 
```node
yarn run v1.22.17
$ nodemon src/cli/cli.ts api
[nodemon] 2.0.19
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/cli/cli.ts api`
/opt/homebrew/var/www/blockchain/sismo-hub/src/infrastructure/file-store/s3-file-store.ts:12
        this.bucketName = options.bucketName ?? "local";
                                              ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module.m._compile (/opt/homebrew/var/www/blockchain/sismo-hub/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/opt/homebrew/var/www/blockchain/sismo-hub/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/homebrew/var/www/blockchain/sismo-hub/src/infrastructure/file-store/index.ts:3:1)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by leosayous21** [comment]
Hey @Sigri44, thanks for pointing this out! 
I can't reproduce the error on my side. 
What is your node version?

```bash
node --version
```
Thanks

**Comment by Sigri44** [comment]
`v12.22.11`

**Comment by leosayous21** [comment]
Can you try to upgrade in version `v16` ?

**Comment by Sigri44** [comment]
Fixed with `v18`, thx !

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/9304947/200166553-2b95866f-3d2b-4caf-90af-90ba88082198.png">
