### ISSUE TITLE
Error when generating group

### ISSUE THREAD

**Issue by Sigri44** [sismo-core/sismo-hub#298]
After follow tutorial topic, when i want to generate group :

```node
$ node -v    
v18.11.0

$ yarn generate-group 0xdigger_lens_followers
yarn run v1.22.19
$ node --require ts-node/register/transpile-only src/cli/cli.ts generate-group 0xdigger_lens_followers
Generating groups (0xdigger_lens_followers)
/opt/homebrew/var/www/blockchain/sismo-hub/src/topics/group-generator/group-generator.ts:116
    const groups = await generator.generate(context, this.groupStore);
                                   ^
TypeError: Cannot read properties of undefined (reading 'generate')
    at GroupGeneratorService.generateGroups (/opt/homebrew/var/www/blockchain/sismo-hub/src/topics/group-generator/group-generator.ts:116:36)
    at async DataSourcesCmd.generateGroup (/opt/homebrew/var/www/blockchain/sismo-hub/src/topics/group-generator/group-generator.commands.ts:47:3)
    at async Command.parseAsync (/opt/homebrew/var/www/blockchain/sismo-hub/node_modules/commander/lib/command.js:917:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by leosayous21** [comment]
Hey @Sigri44 , did you registered your group in `group-generators/generators/index.ts` ?

**Comment by Sigri44** [comment]
Thank you, miss add this information : https://docs.sismo.io/sismo-docs/devs-technical-doc/sismo-hub/group-generators
